import { chromium } from "playwright";
const WEB = "http://localhost:8191", API = "http://localhost:4000/v1";
const j = async r => { const t = await r.text(); try { return JSON.parse(t) } catch { return t } };
const post = (p,b,a)=>fetch(API+p,{method:"POST",headers:{"content-type":"application/json",...(a?{authorization:"Bearer "+a}:{})},body:JSON.stringify(b)}).then(j);
const email = `dbg${Date.now()}@test.local`;
const { data: { jwt } } = await post("/auth/email/verify", { email, code: "000000" });
await post("/auth/age-gate", { birthYear: 1995, locale: "en" }, jwt);
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await b.newPage({ viewport:{width:420,height:900} });
page.on("console", m => console.log("[console]", m.type(), m.text().slice(0,400)));
page.on("pageerror", e => console.log("[pageerror]", String(e).slice(0,600)));
await page.addInitScript(([k,v])=>localStorage.setItem(k,v), ["rpgllm.jwt", jwt]);
await page.goto(WEB+"/onboarding/scenario", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(4000);
console.log("BODY:", (await page.innerText("body")).slice(0,600));
await page.screenshot({path:"/tmp/shots-m2/dbg.png"});
await b.close();
