/** Single source of truth for data-testid. Client sets, E2E reads. */
export const T = {
  // SCR-002
  authEmailBtn: "auth-provider-email",
  authEmailInput: "auth-email-input",
  authCodeInput: "auth-code-input",
  authSubmit: "auth-submit",
  ageYearInput: "age-year-input",
  ageContinue: "age-continue",
  ageBlocked: "age-blocked",
  localeToggle: "locale-toggle",
  // SCR-003/004/005/006
  worldCard: (slug: string) => `world-card-${slug}`,
  personaPreset: (handle: string) => `persona-${handle}`,
  personaCreateOwn: "persona-create-own",
  personaContinue: "persona-continue",
  personaHandleInput: "persona-handle-input",
  personaNameInput: "persona-name-input",
  personaBioInput: "persona-bio-input",
  personaSave: "persona-save",
  follower: (handle: string) => `follower-${handle}`,
  enterWorld: "enter-world",
  worldLoading: "world-loading",
  // SCR-010
  feedList: "feed-list",
  post: (id: string) => `post-${id}`,
  postText: "post-text",
  postAuthor: "post-author",
  postKind: (kind: string) => `post-kind-${kind}`,
  composeFab: "compose-fab",
  energyBadge: "energy-badge",
  eventBanner: "event-banner",
  statToast: "stat-toast",
  fallbackToast: "fallback-toast",
  tabFeed: "tab-feed",
  tabDms: "tab-dms",
  // SCR-011
  composeInput: "compose-input",
  composeSubmit: "compose-submit",
  composeCancel: "compose-cancel",
  safetyError: "safety-error",
  // SCR-012
  threadReply: (id: string) => `reply-${id}`,
  rateDown: (id: string) => `rate-down-${id}`,
  rateUp: (id: string) => `rate-up-${id}`,
  loadMore: "load-more",
  replyBtn: "reply-btn",
  // SCR-013
  statCard: "stat-card",
  statNarrative: "stat-narrative",
  statAura: "stat-aura",
  statFollowers: "stat-followers",
  statHumor: "stat-humor",
  statContinue: "stat-continue",
  // SCR-014
  eventCard: "event-card",
  eventPrompt: "event-prompt",
  eventChoice: (i: number) => `event-choice-${i}`,
  // SCR-020/021
  dmNew: "dm-new",
  dmThread: (id: string) => `dm-thread-${id}`,
  dmChar: (handle: string) => `dm-char-${handle}`,
  dmInput: "dm-input",
  dmSend: "dm-send",
  dmBubble: "dm-bubble",
  dmTyping: "dm-typing",
  dmAffinity: "dm-affinity",
  // SCR-030
  paywall: "paywall",
  plan: (id: string) => `plan-${id}`,
  paywallContinue: "paywall-continue",
  paywallClose: "paywall-close",
  paywallSuccess: "paywall-success",
  // SCR-032
  energyModal: "energy-modal",
  energyValue: "energy-value",
  watchAd: "watch-ad",
  useCoffee: "use-coffee",
  getPlus: "get-plus",
  refillTimer: "refill-timer",
} as const;
