/** Single source of truth for data-testid. Client sets, E2E reads. */
export const T = {
  // SCR-002
  authEmailBtn: "auth-provider-email",
  authEmailInput: "auth-email-input",
  authCodeInput: "auth-code-input",
  authSubmit: "auth-submit",
  ageYearInput: "age-year-input",
  ageContinue: "age-continue",
  ageBlocked: "age-blocked",
  localeToggle: "locale-toggle",
  // SCR-003/004/005/006
  worldCard: (slug: string) => `world-card-${slug}`,
  personaPreset: (handle: string) => `persona-${handle}`,
  personaCreateOwn: "persona-create-own",
  personaContinue: "persona-continue",
  personaHandleInput: "persona-handle-input",
  personaNameInput: "persona-name-input",
  personaBioInput: "persona-bio-input",
  personaSave: "persona-save",
  follower: (handle: string) => `follower-${handle}`,
  enterWorld: "enter-world",
  worldLoading: "world-loading",
  // SCR-010
  feedList: "feed-list",
  post: (id: string) => `post-${id}`,
  postText: "post-text",
  postAuthor: "post-author",
  postKind: (kind: string) => `post-kind-${kind}`,
  composeFab: "compose-fab",
  energyBadge: "energy-badge",
  eventBanner: "event-banner",
  statToast: "stat-toast",
  fallbackToast: "fallback-toast",
  tabFeed: "tab-feed",
  tabDms: "tab-dms",
  // SCR-011
  composeInput: "compose-input",
  composeSubmit: "compose-submit",
  composeCancel: "compose-cancel",
  safetyError: "safety-error",
  // SCR-012
  threadReply: (id: string) => `reply-${id}`,
  rateDown: (id: string) => `rate-down-${id}`,
  rateUp: (id: string) => `rate-up-${id}`,
  loadMore: "load-more",
  replyBtn: "reply-btn",
  // SCR-013
  statCard: "stat-card",
  statNarrative: "stat-narrative",
  statAura: "stat-aura",
  statFollowers: "stat-followers",
  statHumor: "stat-humor",
  statContinue: "stat-continue",
  // SCR-014
  eventCard: "event-card",
  eventPrompt: "event-prompt",
  eventChoice: (i: number) => `event-choice-${i}`,
  // SCR-020/021
  dmNew: "dm-new",
  dmThread: (id: string) => `dm-thread-${id}`,
  dmChar: (handle: string) => `dm-char-${handle}`,
  dmInput: "dm-input",
  dmSend: "dm-send",
  dmBubble: "dm-bubble",
  dmTyping: "dm-typing",
  dmAffinity: "dm-affinity",
  // SCR-030
  paywall: "paywall",
  plan: (id: string) => `plan-${id}`,
  paywallContinue: "paywall-continue",
  paywallClose: "paywall-close",
  paywallSuccess: "paywall-success",
  // SCR-032
  energyModal: "energy-modal",
  energyValue: "energy-value",
  watchAd: "watch-ad",
  useCoffee: "use-coffee",
  getPlus: "get-plus",
  refillTimer: "refill-timer",
  // SCR-026 profile
  tabProfile: "tab-profile",
  profileHandle: "profile-handle",
  profileLevel: "profile-level",
  profileXp: "profile-xp",
  profilePosts: "profile-posts",
  profileRelationship: (handle: string) => `profile-rel-${handle}`,
  // SCR-033 settings
  settingsBtn: "settings-btn",
  settings: "settings",
  settingsLocale: "settings-locale",
  settingsConsent: "settings-consent",
  settingsManageSub: "settings-manage-sub",
  settingsRestore: "settings-restore",
  settingsBlocked: "settings-blocked",
  settingsTerms: "settings-terms",
  settingsPrivacy: "settings-privacy",
  settingsGuidelines: "settings-guidelines",
  settingsExport: "settings-export",
  settingsSignOut: "settings-sign-out",
  settingsDelete: "settings-delete",
  deleteConfirmInput: "delete-confirm-input",
  deleteConfirm: "delete-confirm",
  deleteDone: "delete-done",
  // SCR-037 report / block
  overflow: (id: string) => `overflow-${id}`,
  reportOpen: "report-open",
  reportReason: (reason: string) => `report-reason-${reason}`,
  reportNote: "report-note",
  reportSubmit: "report-submit",
  reportDone: "report-done",
  blockOpen: "block-open",
  blockConfirm: "block-confirm",
  unblock: (handle: string) => `unblock-${handle}`,
  // SCR-038 digest ("While you were away")
  digestCard: "digest-card",
  digestHeadline: "digest-headline",
  digestBody: "digest-body",
  digestDismiss: "digest-dismiss",
  // SCR-039 memory ledger
  memoryOpen: "memory-open",
  memoryLedger: "memory-ledger",
  memorySummary: "memory-summary",
  memoryEntry: (id: string) => `memory-entry-${id}`,
  // SCR-040 shareable moment
  momentCard: "moment-card",
  momentShare: "moment-share",
  momentClose: "moment-close",
  // SCR-041 referral
  referralOpen: "referral-open",
  referralCode: "referral-code",
  referralCopy: "referral-copy",
  referralRedeemInput: "referral-redeem-input",
  referralRedeem: "referral-redeem",
  // Notifications (SCR-042)
  tabNotifications: "tab-notifications",
  notifBadge: "notif-badge",
  notifList: "notif-list",
  notifRow: (id: string) => `notif-${id}`,
  notifMarkAll: "notif-mark-all",
  notifEmpty: "notif-empty",
  // Streak / daily check-in (SCR-043)
  streakChip: "streak-chip",
  streakCard: "streak-card",
  streakDays: "streak-days",
  streakClaim: "streak-claim",
  streakLadderDay: (d: number) => `streak-day-${d}`,
  // Achievements (SCR-044)
  achievementsOpen: "achievements-open",
  achievementsList: "achievements-list",
  achievement: (key: string) => `achievement-${key}`,
  achievementUnlock: "achievement-unlock",
  achievementUnlockClose: "achievement-unlock-close",
  // Level up / milestone celebration (SCR-045)
  celebration: "celebration",
  celebrationTitle: "celebration-title",
  celebrationClose: "celebration-close",
  // Trending / explore (SCR-046)
  tabExplore: "tab-explore",
  trendingList: "trending-list",
  trendingTopic: (label: string) => `trending-${label}`,
  trendingRank: "trending-rank",
  risingCharacter: (handle: string) => `rising-${handle}`,
  // Character profile (SCR-047)
  characterProfile: "character-profile",
  characterFollowState: "character-follow-state",
  characterPosts: "character-posts",
  // Feed richness
  postMedia: (id: string) => `post-media-${id}`,
  postTime: "post-time",
  feedHeader: "feed-header",
  worldChip: "world-chip",
  // World Studio (SCR-048 create / SCR-049 building+ready / SCR-050 my worlds & review)
  studioOpen: "studio-open",
  studioTabButton: "tab-studio",
  studioPremiseInput: "studio-premise-input",
  studioPremiseCount: "studio-premise-count",
  studioGenre: (g: string) => `studio-genre-${g}`,
  studioLocale: (l: string) => `studio-locale-${l}`,
  studioVisibility: (v: string) => `studio-visibility-${v}`,
  studioCreate: "studio-create",
  studioCost: "studio-cost",
  studioRemaining: "studio-remaining",
  studioError: "studio-error",
  studioBuilding: "studio-building",
  studioProgress: "studio-progress",
  studioStep: (key: string) => `studio-step-${key}`,
  studioReady: "studio-ready",
  studioCast: "studio-cast",
  studioCastMember: (handle: string) => `studio-cast-${handle}`,
  studioPlay: "studio-play",
  studioPublish: "studio-publish",
  studioKeepPrivate: "studio-keep-private",
  studioStatusBadge: "studio-status-badge",
  studioFailed: "studio-failed",
  studioRetry: "studio-retry",
  studioMyWorlds: "studio-my-worlds",
  studioMyWorldCard: (slug: string) => `studio-world-${slug}`,
  studioMyWorldsEmpty: "studio-my-worlds-empty",
  communityWorlds: "community-worlds",
  communityWorldCard: (slug: string) => `community-world-${slug}`,
  communityWorldsEmpty: "community-worlds-empty",
  worldReviewQueue: "world-review-queue",
  worldReviewCard: (id: string) => `world-review-${id}`,
  worldReviewApprove: (id: string) => `world-review-approve-${id}`,
  worldReviewReject: (id: string) => `world-review-reject-${id}`,
  worldReviewReason: "world-review-reason",
  worldReviewEmpty: "world-review-empty",
  worldReviewOverdue: "world-review-overdue",
  worldReviewReports: (id: string) => `world-review-reports-${id}`,
  reportWorld: "report-world",
} as const;
